import turtle
turtle.pen(pencolor='blue',fillcolor='blue')
turtle.begin_fill()
turtle.circle(60)
turtle.end_fill()
turtle.right(60)
turtle.forward(20)
turtle.right(120)
turtle.forward(20)
turtle.right(120)
turtle.forward(20)
turtle.pencolor('black')
turtle.right(150)
turtle.forward(70)
turtle.circle(150,40)
turtle.hideturtle()
turtle.mainloop()