import turtle

turtle.shape("circle")
turtle.pen(pencolor="brown", fillcolor="red", pensize=2)
turtle.forward(100)
turtle.left(120)
turtle.forward(100)
turtle.stamp()
turtle.left(120)
turtle.forward(100)
turtle.left(30)
turtle.pencolor('black')
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.hideturtle()
turtle.mainloop()
